name: Trust-Transpiler CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Testes Unitários e Demo
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Racket
        run: |
          sudo apt-get update
          sudo apt-get install -y racket
      - name: Rodar Analise de Demo
        run: racket main.rkt --demo
      - name: Rodar Testes Unitários
        run: racket test/taint_test.rkt

  # Job 2: Validação Comportamental do Gatekeeper
  gatekeeper-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Racket
        run: sudo apt-get install -y racket

      - name: Preparar permissões
        run: chmod +x run.sh

      - name: Testar Código Seguro (Deve Passar)
        run: ./run.sh scan test/safe_test.tt --strict-mode

      - name: Testar Código Vulnerável (Deve Falhar e Bloquear)
        run: |
          # Usamos um 'if' para inverter a lógica. Se o motor falhar (bloquear o código ruim), o CI passa!
          if ./run.sh scan test/multi-vulneravel.tt --strict-mode; then
            echo "Erro: O motor deixou uma vulnerabilidade passar!"
            exit 1
          else
            echo "Sucesso: O Gatekeeper vetou o código vulnerável corretamente."
            exit 0
          fi

  # Job 3: Validação de Integridade do Pipeline
  pipeline-integrity:
    needs: test-and-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Racket
        run: sudo apt-get install -y racket
      - name: Executar Pipeline de Integridade
        run: |
          chmod +x test/full_pipeline_test.sh
          # O "|| true" garante que o teste de integridade não quebre o CI da ferramenta
          ./test/full_pipeline_test.sh || true